services:
  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    ports:
      - "8080:8080"
    develop:
      watch:
        - path: ./packages/api
          action: rebuild
          target: /app/packages/api
          ignore:
            - node_modules/
        - path: ./packages/database
          action: rebuild
          target: /app/packages/database
          ignore:
            - node_modules/
        - path: .env.local
          action: rebuild
    env_file:
      - .env.local
    depends_on:
      - migrator
  web:
    build:
      context: .
      dockerfile: packages/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_HOST_URL=http://api:8080
    develop:
       watch:
        - path: ./packages/web
          action: rebuild
          target: /app/packages/web
          ignore:
            - node_modules/
        - path: .env.local
          action: rebuild
  migrator:
    build:
      context: .
      dockerfile: packages/database/Dockerfile.migrator
    env_file:
      - .env.local
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.local
  db-admin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    env_file:
      - .env.local
    depends_on:
      - db


volumes:
  postgres-data: