services:
  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: ./packages/api
          action: sync
          target: /app/packages/api
          ignore:
            - node_modules/
        - path: ./packages/database
          action: sync
          target: /app/packages/database
          ignore:
            - node_modules/
        - path: ./packages/api/package.json
          action: rebuild
    env_file:
      - .env.prod
    depends_on:
      - migrator
    networks:
      - internal_network

  migrator:
    build:
      context: .
      dockerfile: packages/database/Dockerfile.migrator
    env_file:
      - .env.prod
    depends_on:
      - db
    networks:
      - internal_network

  db:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.prod
    networks:
      - internal_network
  db-admin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    env_file:
      - .env.prod
    depends_on:
      - db
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge

volumes:
  postgres-data: